language: python
python:
  - {{{ python.version }}}

install:
  - make python=$( which python ) .installed.cfg
  - bin/develop checkout niteoweb.ipn.core
  - make python=$( which python ) .installed.cfg

script:
  - make tests

notifications:
  irc:
    - "{{{ author.irc }}}"
